// The Round-3 break-the-fixes and state-torture corpora, authored in the
// August 2026 campaign (docs/qa/fuzz-campaign-2026-08.md). This Swift file is
// the source of truth — the JSON corpora and generator script it was first
// mechanized from were never checked in. Edit rows in place.
// Rows reuse the FuzzCorpusRow struct declared in FuzzCorpusR1Data.swift and
// are interpreted at test runtime by FuzzCorpusR2.swift.
import Foundation

enum FuzzCorpusR2Data {

    static let rows_breakfixes: [FuzzCorpusRow] = [
        FuzzCorpusRow(source: "breakfixes", index: 0, utterance: "reddit please, twenty minutes", stateSpec: nil, expect: "VERDICT WRITE_IT_OUT door=reddit minutes=20"),
        FuzzCorpusRow(source: "breakfixes", index: 1, utterance: "ok fine. tiktok. fifteen", stateSpec: nil, expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=15"),
        FuzzCorpusRow(source: "breakfixes", index: 2, utterance: "tiktok 10; instagram", stateSpec: nil, expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=10"),
        FuzzCorpusRow(source: "breakfixes", index: 3, utterance: "give me 20 of the gram, instagram i mean", stateSpec: nil, expect: "VERDICT GRANT door=instagram minutes=20"),
        FuzzCorpusRow(source: "breakfixes", index: 4, utterance: "an hour of tiktok and instagram", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 5, utterance: "half an hour, reddit please", stateSpec: nil, expect: "VERDICT WRITE_IT_OUT door=reddit minutes=30"),
        FuzzCorpusRow(source: "breakfixes", index: 6, utterance: "an hour on insta, then tiktok", stateSpec: nil, expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=60"),
        FuzzCorpusRow(source: "breakfixes", index: 7, utterance: "quarter of an hour on the gram, ig i mean", stateSpec: nil, expect: "VERDICT SILENCE"),
        FuzzCorpusRow(source: "breakfixes", index: 8, utterance: "instagram, tiktok ten", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 9, utterance: "20 minutes, tiktok or instagram", stateSpec: nil, expect: "NEVER_LOOSEN"),
        FuzzCorpusRow(source: "breakfixes", index: 10, utterance: "tiktok is my weakness, give me 15 of reddit", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 11, utterance: ",,,, tiktok ,,, ten ,,,,", stateSpec: nil, expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=10"),
        FuzzCorpusRow(source: "breakfixes", index: 12, utterance: "cap tiktok, give me 20 of instagram", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 13, utterance: "give me 20 of instagram, cap tiktok", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 14, utterance: "put a cap on insta", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 15, utterance: "limit insta - 25 max", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 16, utterance: "i want a cap on youtube", stateSpec: nil, expect: "VERDICT SILENCE"),
        FuzzCorpusRow(source: "breakfixes", index: 17, utterance: "im at my limit on tiktok, give me 20 minutes", stateSpec: nil, expect: "VERDICT GRANT door=tiktok minutes=20"),
        FuzzCorpusRow(source: "breakfixes", index: 18, utterance: "theres a cap on tiktok, give me 15 of tiktok", stateSpec: nil, expect: "VERDICT GRANT door=tiktok minutes=15"),
        FuzzCorpusRow(source: "breakfixes", index: 19, utterance: "remove instagram, no cap on tiktok", stateSpec: nil, expect: "VERDICT RULE_CHANGE polarity=tighten doors-=instagram"),
        FuzzCorpusRow(source: "breakfixes", index: 20, utterance: "hey, remove instagram, no cap on tiktok", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 21, utterance: "never any limit on reddit", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 22, utterance: "gimme 20 of insta, cap the gram", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 23, utterance: "i want a cap on tiktok, gimme 15 of reddit", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 24, utterance: "cap tiktok at an hour", stateSpec: nil, expect: "PARSE SET_CAP door=tiktok minutes=60"),
        FuzzCorpusRow(source: "breakfixes", index: 25, utterance: "no more instagram at night", stateSpec: nil, expect: "VERDICT CLOSE door=instagram until=day-boundary"),
        FuzzCorpusRow(source: "breakfixes", index: 26, utterance: "shut tiktok at night until 9", stateSpec: nil, expect: "VERDICT CLOSE door=tiktok until=21:00"),
        FuzzCorpusRow(source: "breakfixes", index: 27, utterance: "ban tiktok at night", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 28, utterance: "can i have tiktok at night", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 29, utterance: "give me an hour of tiktok at night", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 30, utterance: "close everything at night", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 31, utterance: "night starts at 11", stateSpec: nil, expect: "VERDICT RULE_CHANGE polarity=loosen downStart=23:00"),
        FuzzCorpusRow(source: "breakfixes", index: 32, utterance: "cut off youtube at night", stateSpec: nil, expect: "VERDICT CLOSE door=youtube until=day-boundary"),
        FuzzCorpusRow(source: "breakfixes", index: 33, utterance: "shut reddit until 0", stateSpec: nil, expect: "PARSE CLOSE door=reddit until=0:00"),
        FuzzCorpusRow(source: "breakfixes", index: 34, utterance: "close youtube until 24", stateSpec: nil, expect: "PARSE CLOSE door=youtube until=0:00"),
        FuzzCorpusRow(source: "breakfixes", index: 35, utterance: "block insta until 00", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 36, utterance: "close tiktok until 12", stateSpec: nil, expect: "PARSE CLOSE door=tiktok until=12:00"),
        FuzzCorpusRow(source: "breakfixes", index: 37, utterance: "close tiktok until midnight", stateSpec: nil, expect: "VERDICT CLOSE door=tiktok until=day-boundary"),
        FuzzCorpusRow(source: "breakfixes", index: 38, utterance: "shut youtube until 0:30", stateSpec: nil, expect: "PARSE CLOSE door=youtube until=0:30"),
        FuzzCorpusRow(source: "breakfixes", index: 39, utterance: "close tiktok until 9.30", stateSpec: nil, expect: "PARSE CLOSE door=tiktok until=21:00"),
        FuzzCorpusRow(source: "breakfixes", index: 40, utterance: "close tiktok until 25", stateSpec: nil, expect: "VERDICT CLOSE door=tiktok until=day-boundary"),
        FuzzCorpusRow(source: "breakfixes", index: 41, utterance: "shut tiktok until zero", stateSpec: nil, expect: "VERDICT CLOSE door=tiktok until=day-boundary"),
        FuzzCorpusRow(source: "breakfixes", index: 42, utterance: "down hours till 0", stateSpec: nil, expect: "VERDICT RULE_CHANGE polarity=loosen downEnd=0:00"),
        FuzzCorpusRow(source: "breakfixes", index: 43, utterance: "down hours till 24", stateSpec: nil, expect: "PARSE SET_DOWN_END 0:00"),
        FuzzCorpusRow(source: "breakfixes", index: 44, utterance: "let me have 5 or 10 of insta", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 45, utterance: "give me instagram until i leave the gym, 20 minutes tops", stateSpec: nil, expect: "VERDICT GRANT door=instagram minutes=20"),
        FuzzCorpusRow(source: "breakfixes", index: 46, utterance: "give me instagram until i leave the gym, ten or twenty minutes", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 47, utterance: "tiktok 10-15", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 48, utterance: "instagram 10, actually 20", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 49, utterance: "give me an hour or two of tiktok", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 50, utterance: "unlock reddit", stateSpec: nil, expect: "VERDICT WRITE_IT_OUT door=reddit minutes=none"),
        FuzzCorpusRow(source: "breakfixes", index: 51, utterance: "tiktok between 10 and 20", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 52, utterance: "drop instagram's cap", stateSpec: "state: caps={instagram:10}", expect: "VERDICT RULE_CHANGE polarity=loosen cap[instagram]=none"),
        FuzzCorpusRow(source: "breakfixes", index: 53, utterance: "remove tiktok's's limit", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 54, utterance: "remove the gram's cap", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 55, utterance: "instagram's ten", stateSpec: nil, expect: "VERDICT WRITE_IT_OUT door=instagram minutes=10"),
        FuzzCorpusRow(source: "breakfixes", index: 56, utterance: "instagram's limit went to 45", stateSpec: nil, expect: "NEVER_LOOSEN"),
        FuzzCorpusRow(source: "breakfixes", index: 57, utterance: "tiktok's 20 a day", stateSpec: nil, expect: "VERDICT RULE_CHANGE polarity=tighten cap[tiktok]=20"),
        FuzzCorpusRow(source: "breakfixes", index: 58, utterance: "instagram's cap to 30", stateSpec: nil, expect: "VERDICT RULE_CHANGE polarity=tighten cap[instagram]=30"),
        FuzzCorpusRow(source: "breakfixes", index: 59, utterance: "tiktoks s 20 a day", stateSpec: nil, expect: "PARSE SET_CAP door=tiktok minutes=20"),
        FuzzCorpusRow(source: "breakfixes", index: 60, utterance: "remove the apps limit on tiktok", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 61, utterance: "uncap instagram rn", stateSpec: "state: caps={instagram:10}", expect: "VERDICT RULE_CHANGE polarity=loosen cap[instagram]=none"),
        FuzzCorpusRow(source: "breakfixes", index: 62, utterance: "no limit on tiktok tbh", stateSpec: "state: caps={tiktok:10}", expect: "VERDICT RULE_CHANGE polarity=loosen cap[tiktok]=none"),
        FuzzCorpusRow(source: "breakfixes", index: 63, utterance: "drop the reddit cap lol", stateSpec: "state: caps={reddit:15}", expect: "VERDICT RULE_CHANGE polarity=loosen cap[reddit]=none"),
        FuzzCorpusRow(source: "breakfixes", index: 64, utterance: "no cap on tiktok istg", stateSpec: nil, expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "breakfixes", index: 65, utterance: "tiktok 20 fr", stateSpec: nil, expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=20"),
        FuzzCorpusRow(source: "breakfixes", index: 66, utterance: "tiktok 20 a day ngl", stateSpec: nil, expect: "VERDICT RULE_CHANGE polarity=tighten cap[tiktok]=20"),
        FuzzCorpusRow(source: "breakfixes", index: 67, utterance: "block instagram fr fr", stateSpec: nil, expect: "VERDICT CLOSE door=instagram until=day-boundary"),
        FuzzCorpusRow(source: "breakfixes", index: 68, utterance: "no more youtube rn", stateSpec: nil, expect: "VERDICT CLOSE door=youtube until=day-boundary"),
        FuzzCorpusRow(source: "breakfixes", index: 69, utterance: "uncap tiktok no cap", stateSpec: "state: caps={tiktok:10}", expect: "VERDICT RULE_CHANGE polarity=loosen cap[tiktok]=none"),
    ]

    static let rows_statetorture: [FuzzCorpusRow] = [
        FuzzCorpusRow(source: "statetorture", index: 0, utterance: "insta ten", stateSpec: "state: budget=0", expect: "VERDICT SILENCE"),
        FuzzCorpusRow(source: "statetorture", index: 1, utterance: "status", stateSpec: "state: budget=0", expect: "VERDICT STATUS remaining=0"),
        FuzzCorpusRow(source: "statetorture", index: 2, utterance: "set my budget to 30", stateSpec: "state: budget=0", expect: "VERDICT RULE_CHANGE polarity=loosen budget=30"),
        FuzzCorpusRow(source: "statetorture", index: 3, utterance: "twenty minutes of tiktok", stateSpec: "state: budget=1", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=20"),
        FuzzCorpusRow(source: "statetorture", index: 4, utterance: "youtube 25", stateSpec: "state: spent={tiktok:39}", expect: "VERDICT WRITE_IT_OUT door=youtube minutes=25"),
        FuzzCorpusRow(source: "statetorture", index: 5, utterance: "quarter of an hour on reddit", stateSpec: "state: spent={tiktok:39}", expect: "VERDICT WRITE_IT_OUT door=reddit minutes=15"),
        FuzzCorpusRow(source: "statetorture", index: 6, utterance: "youtube five", stateSpec: "state: spent={tiktok:25,instagram:15}", expect: "VERDICT REFUSE_NOTHING_LEFT"),
        FuzzCorpusRow(source: "statetorture", index: 7, utterance: "tiktok forty", stateSpec: "state: budget=40", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=40"),
        FuzzCorpusRow(source: "statetorture", index: 8, utterance: "tiktok 41", stateSpec: "state: budget=40", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=41"),
        FuzzCorpusRow(source: "statetorture", index: 9, utterance: "tiktok ten", stateSpec: "state: live={tiktok:40@14:30}", expect: "VERDICT REFUSE_NOTHING_LEFT"),
        FuzzCorpusRow(source: "statetorture", index: 10, utterance: "youtube 28", stateSpec: "state: caps={youtube:30} spent={tiktok:25}", expect: "VERDICT WRITE_IT_OUT door=youtube minutes=28"),
        FuzzCorpusRow(source: "statetorture", index: 11, utterance: "youtube 40", stateSpec: "state: caps={youtube:15} spent={tiktok:25}", expect: "VERDICT WRITE_IT_OUT door=youtube minutes=40"),
        FuzzCorpusRow(source: "statetorture", index: 12, utterance: "forty minutes of youtube", stateSpec: "state: caps={youtube:5} spent={tiktok:25}", expect: "VERDICT WRITE_IT_OUT door=youtube minutes=40"),
        FuzzCorpusRow(source: "statetorture", index: 13, utterance: "tiktok 60", stateSpec: "state: caps={tiktok:25} spent={tiktok:10,instagram:10}", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=60"),
        FuzzCorpusRow(source: "statetorture", index: 14, utterance: "10 minutes of tiktok", stateSpec: "state: caps={tiktok:10} spent={tiktok:9}", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=10"),
        FuzzCorpusRow(source: "statetorture", index: 15, utterance: "insta fifteen", stateSpec: "state: caps={instagram:15}", expect: "VERDICT SILENCE"),
        FuzzCorpusRow(source: "statetorture", index: 16, utterance: "insta five", stateSpec: "state: caps={tiktok:10,instagram:10} spent={tiktok:10}", expect: "VERDICT SILENCE"),
        FuzzCorpusRow(source: "statetorture", index: 17, utterance: "tiktok five", stateSpec: "state: caps={tiktok:10} spent={tiktok:10} closed={tiktok@18:00}", expect: "VERDICT REFUSE_DOOR_CLOSED door=tiktok until=day-boundary"),
        FuzzCorpusRow(source: "statetorture", index: 18, utterance: "half an hour of insta", stateSpec: "state: caps={instagram:10}", expect: "VERDICT SILENCE"),
        FuzzCorpusRow(source: "statetorture", index: 19, utterance: "give me 20 of the gram, instagram i mean", stateSpec: "state: caps={instagram:10}", expect: "VERDICT GRANT door=instagram minutes=10 relock=+10m"),
        FuzzCorpusRow(source: "statetorture", index: 20, utterance: "insta for 15", stateSpec: "state: closed={tiktok}", expect: "VERDICT SILENCE"),
        FuzzCorpusRow(source: "statetorture", index: 21, utterance: "tiktok ten", stateSpec: "state: closed={tiktok@15:30}", expect: "VERDICT REFUSE_DOOR_CLOSED door=tiktok until=15:30"),
        FuzzCorpusRow(source: "statetorture", index: 22, utterance: "gimme 10 of tiktok", stateSpec: "state: closed={tiktok@15:30} ; now=16:00", expect: "VERDICT GRANT door=tiktok minutes=10 relock=+10m"),
        FuzzCorpusRow(source: "statetorture", index: 23, utterance: "ten minutes of tiktok", stateSpec: "state: closed={tiktok@15:00}", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=10"),
        FuzzCorpusRow(source: "statetorture", index: 24, utterance: "let me have some reddit", stateSpec: "state: closed={reddit}", expect: "VERDICT REFUSE_DOOR_CLOSED door=reddit until=day-boundary"),
        FuzzCorpusRow(source: "statetorture", index: 25, utterance: "let me keep insta while im at work", stateSpec: "state: spent={tiktok:40}", expect: "VERDICT SILENCE"),
        FuzzCorpusRow(source: "statetorture", index: 26, utterance: "tiktok for five", stateSpec: "state: live={tiktok:20@14:45}", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=5"),
        FuzzCorpusRow(source: "statetorture", index: 27, utterance: "tiktok six", stateSpec: "state: live={tiktok:20@14:45}", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=6"),
        FuzzCorpusRow(source: "statetorture", index: 28, utterance: "tiktok 5", stateSpec: "state: caps={tiktok:10} live={tiktok:10@14:55}", expect: "VERDICT REFUSE_DOOR_CLOSED door=tiktok until=day-boundary"),
        FuzzCorpusRow(source: "statetorture", index: 29, utterance: "10 of tiktok", stateSpec: "state: live={instagram:35@14:50}", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=10"),
        FuzzCorpusRow(source: "statetorture", index: 30, utterance: "another 10 of tiktok", stateSpec: "state: live={tiktok:10@14:50}", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=10"),
        FuzzCorpusRow(source: "statetorture", index: 31, utterance: "tiktok 4", stateSpec: "state: live={tiktok:10@21:50} ; now=21:55", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=4"),
        FuzzCorpusRow(source: "statetorture", index: 32, utterance: "tiktok twenty", stateSpec: "now=21:59", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=20"),
        FuzzCorpusRow(source: "statetorture", index: 33, utterance: "tiktok twenty", stateSpec: "now=22:00", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=20"),
        FuzzCorpusRow(source: "statetorture", index: 34, utterance: "tiktok twenty", stateSpec: "now=22:01", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=20"),
        FuzzCorpusRow(source: "statetorture", index: 35, utterance: "instagram ten", stateSpec: "now=6:59", expect: "VERDICT WRITE_IT_OUT door=instagram minutes=10"),
        FuzzCorpusRow(source: "statetorture", index: 36, utterance: "instagram ten", stateSpec: "now=7:00", expect: "VERDICT WRITE_IT_OUT door=instagram minutes=10"),
        FuzzCorpusRow(source: "statetorture", index: 37, utterance: "tiktok ten", stateSpec: "now=21:50", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=10"),
        FuzzCorpusRow(source: "statetorture", index: 38, utterance: "an hour of youtube", stateSpec: "now=21:30", expect: "VERDICT WRITE_IT_OUT door=youtube minutes=60"),
        FuzzCorpusRow(source: "statetorture", index: 39, utterance: "reddit 20", stateSpec: "state: caps={reddit:5} ; now=21:50", expect: "VERDICT WRITE_IT_OUT door=reddit minutes=20"),
        FuzzCorpusRow(source: "statetorture", index: 40, utterance: "tiktok 25", stateSpec: "state: spent={tiktok:37} ; now=21:50", expect: "VERDICT WRITE_IT_OUT door=tiktok minutes=25"),
        FuzzCorpusRow(source: "statetorture", index: 41, utterance: "tiktok one", stateSpec: "state: budget=0 caps={tiktok:1} closed={tiktok} ; now=23:00", expect: "VERDICT REFUSE_NOTHING_LEFT"),
        FuzzCorpusRow(source: "statetorture", index: 42, utterance: "done with reddit", stateSpec: "now=22:30", expect: "VERDICT CLOSE door=reddit until=day-boundary"),
        FuzzCorpusRow(source: "statetorture", index: 43, utterance: "block reddit until 5 am", stateSpec: "now=23:00", expect: "VERDICT CLOSE door=reddit until=5:00"),
        FuzzCorpusRow(source: "statetorture", index: 44, utterance: "shut tiktok until 9", stateSpec: "now=23:00", expect: "VERDICT CLOSE door=tiktok until=day-boundary"),
        FuzzCorpusRow(source: "statetorture", index: 45, utterance: "cut my budget to 5", stateSpec: "state: spent={tiktok:40} ; now=23:00", expect: "VERDICT RULE_CHANGE polarity=tighten budget=5"),
        FuzzCorpusRow(source: "statetorture", index: 46, utterance: "cap tiktok at 6", stateSpec: "state: closed={tiktok}", expect: "VERDICT RULE_CHANGE polarity=tighten cap[tiktok]=6"),
        FuzzCorpusRow(source: "statetorture", index: 47, utterance: "set my budget to 40", stateSpec: "state: budget=40", expect: "VERDICT RULE_CHANGE polarity=unchanged budget=40"),
        FuzzCorpusRow(source: "statetorture", index: 48, utterance: "30 a day", stateSpec: "state: budget=30", expect: "VERDICT RULE_CHANGE polarity=unchanged budget=30"),
        FuzzCorpusRow(source: "statetorture", index: 49, utterance: "cap tiktok at 10", stateSpec: "state: caps={tiktok:10}", expect: "VERDICT RULE_CHANGE polarity=unchanged cap[tiktok]=10"),
        FuzzCorpusRow(source: "statetorture", index: 50, utterance: "cap tiktok at 11", stateSpec: "state: caps={tiktok:10}", expect: "VERDICT RULE_CHANGE polarity=loosen cap[tiktok]=11"),
        FuzzCorpusRow(source: "statetorture", index: 51, utterance: "cap reddit at 39", stateSpec: "state: caps={tiktok:10,instagram:10}", expect: "VERDICT RULE_CHANGE polarity=tighten cap[reddit]=39"),
        FuzzCorpusRow(source: "statetorture", index: 52, utterance: "bump the youtube cap to 20", stateSpec: "state: caps={youtube:5}", expect: "VERDICT RULE_CHANGE polarity=loosen cap[youtube]=20"),
        FuzzCorpusRow(source: "statetorture", index: 53, utterance: "lift the limit on reddit", stateSpec: "state: caps={reddit:15}", expect: "VERDICT RULE_CHANGE polarity=loosen cap[reddit]=none"),
        FuzzCorpusRow(source: "statetorture", index: 54, utterance: "take the cap off tiktok", stateSpec: "state: caps={tiktok:10} spent={tiktok:15}", expect: "VERDICT RULE_CHANGE polarity=loosen cap[tiktok]=none"),
        FuzzCorpusRow(source: "statetorture", index: 55, utterance: "uncap youtube", stateSpec: "state: caps={tiktok:10,instagram:10}", expect: "VERDICT RULE_CHANGE polarity=unchanged cap[youtube]=none"),
        FuzzCorpusRow(source: "statetorture", index: 56, utterance: "remove youtube", stateSpec: "state: caps={youtube:10}", expect: "VERDICT RULE_CHANGE polarity=tighten doors-=youtube"),
        FuzzCorpusRow(source: "statetorture", index: 57, utterance: "remove instagram, no cap on tiktok", stateSpec: "state: caps={tiktok:10}", expect: "VERDICT RULE_CHANGE polarity=tighten doors-=instagram"),
        FuzzCorpusRow(source: "statetorture", index: 58, utterance: "remove tiktok, its cap is 10", stateSpec: "state: caps={tiktok:10}", expect: "VERDICT RULE_CHANGE polarity=tighten doors-=tiktok"),
        FuzzCorpusRow(source: "statetorture", index: 59, utterance: "add snapchat", stateSpec: "state: budget=0 ; now=23:00", expect: "VERDICT REFUSE_DOOR_NEEDS_APP"),
        FuzzCorpusRow(source: "statetorture", index: 60, utterance: "down hours start at 10", stateSpec: "state: budget=40", expect: "VERDICT RULE_CHANGE polarity=unchanged downStart=22:00"),
        FuzzCorpusRow(source: "statetorture", index: 61, utterance: "quiet hours till 8", stateSpec: "state: spent={tiktok:40}", expect: "VERDICT REFUSE_AM_OR_PM at=8:00"),
        FuzzCorpusRow(source: "statetorture", index: 62, utterance: "end down hours at 5", stateSpec: "now=23:00", expect: "VERDICT RULE_CHANGE polarity=loosen downEnd=5:00"),
        FuzzCorpusRow(source: "statetorture", index: 63, utterance: "down hours until 7 pm", stateSpec: "state: budget=40", expect: "VERDICT RULE_CHANGE polarity=tighten downEnd=19:00"),
        FuzzCorpusRow(source: "statetorture", index: 64, utterance: "when do my down hours start", stateSpec: "state: budget=0 ; now=23:00", expect: "VERDICT DOWN_HOURS 22:00-7:00"),
        FuzzCorpusRow(source: "statetorture", index: 65, utterance: "hows my balance", stateSpec: "state: live={tiktok:30@14:50}", expect: "VERDICT STATUS remaining=10"),
        FuzzCorpusRow(source: "statetorture", index: 66, utterance: "how much of my tiktok cap is left", stateSpec: "state: caps={tiktok:10} spent={tiktok:4}", expect: "VERDICT STATUS remaining=36"),
        FuzzCorpusRow(source: "statetorture", index: 67, utterance: "no more cap on tiktok", stateSpec: "state: caps={tiktok:10}", expect: "VERDICT CLOSE door=tiktok until=day-boundary"),
        FuzzCorpusRow(source: "statetorture", index: 68, utterance: "i guess theres no cap on tiktok anymore", stateSpec: "state: caps={tiktok:10}", expect: "PARSE UNPARSED-to-widener"),
        FuzzCorpusRow(source: "statetorture", index: 69, utterance: "give me 0 minutes of tiktok", stateSpec: "state: budget=1", expect: "VERDICT SILENCE"),
    ]

    static let rows: [FuzzCorpusRow] = rows_breakfixes + rows_statetorture
}
